In [1]:
import numpy as np

Scalar

In [2]:
x = np.array(42)
print(x.shape)
x.ndim

()


0

In [5]:
x = np.array([1,2,3,4,5,6])
print(x.shape)
x.ndim

(6,)


1

In [6]:
x = np.array([[1,2,3,4,5,6],
              [7,8,9,10,11,12]])
print(x.shape)
x.ndim

(2, 6)


2

In [8]:
x = np.array([[[1,2,3,4,5,6],[7,8,9,10,11,12]],
             [[1,2,3,4,5,6],[7,8,9,10,11,12]],
             [[1,2,3,4,5,6],[7,8,9,10,11,12]]])
print(x.shape)
x.ndim

(3, 2, 6)


3

Reshape

In [10]:
x = np.array([[0,1],[2,3],[4,5],[6,7]])
x.shape

(4, 2)

In [11]:
x.reshape(8,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7]])

In [12]:
x.reshape(2,4)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [13]:
np.transpose(x)

array([[0, 2, 4, 6],
       [1, 3, 5, 7]])

In [14]:
x.T

array([[0, 2, 4, 6],
       [1, 3, 5, 7]])