In [1]:
import torch

In [2]:
A = torch.randn(8,5,3)
A.size()

torch.Size([8, 5, 3])

In [3]:
print(A[0][0][0])
print(A[0,0,:])

tensor(0.7836)
tensor([0.7836, 0.7350, 1.2096])


In [4]:
C = torch.zeros((3,4))

In [5]:
C.dtype

torch.float32

In [6]:
D = torch.randint(2,C.size())
print(D)
print(D.dtype)
print(D.float().dtype)

tensor([[0, 1, 1, 0],
        [0, 0, 0, 1],
        [1, 1, 1, 1]])
torch.int64
torch.float32


In [7]:
C + D

tensor([[0., 1., 1., 0.],
        [0., 0., 0., 1.],
        [1., 1., 1., 1.]])

In [8]:
torch.set_default_tensor_type("torch.FloatTensor")

In [9]:
C.device

device(type='cpu')

In [10]:
torch.cuda.is_available()

True

In [12]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [13]:
x = torch.randn((3,5)) # cpu
y = torch.ones_like(x,device = device) # gpu

In [14]:
x = x.to(device)

In [15]:
z = x+y

In [16]:
print(z)
print(z.cpu())

tensor([[ 2.1527,  0.2691, -0.0528,  0.8300, -0.2003],
        [ 2.5772, -0.0842,  1.2651, -0.6359, -0.8658],
        [ 0.7864,  0.5737,  0.7426,  1.9157,  1.8844]], device='cuda:0')
tensor([[ 2.1527,  0.2691, -0.0528,  0.8300, -0.2003],
        [ 2.5772, -0.0842,  1.2651, -0.6359, -0.8658],
        [ 0.7864,  0.5737,  0.7426,  1.9157,  1.8844]])


In [17]:
from google.colab import drive
drive.mount("/gdrive")

Mounted at /gdrive


In [19]:
from torchvision import datasets


In [21]:
cifar = datasets.CIFAR10("/gdrive/MyDrive/Projectes/Platzi/DeepLearning/Curso de Deep Learning con Pytorch/dl-pytorch/datasets", download=True)

  0%|          | 0/170498071 [00:00<?, ?it/s]

Extracting /gdrive/MyDrive/Projectes/Platzi/DeepLearning/Curso de Deep Learning con Pytorch/dl-pytorch/datasets/cifar-10-python.tar.gz to /gdrive/MyDrive/Projectes/Platzi/DeepLearning/Curso de Deep Learning con Pytorch/dl-pytorch/datasets


In [27]:
cifar.data.shape
data = torch.Tensor(cifar.data)
data.size()

torch.Size([50000, 32, 32, 3])